Repository DO-NOTTO-DO/iOS-NOTTODO, pull requests merged in 2023-02, with the labels that each got.

#4 [Chore] #3 - TabBar 세팅
  iOS-NOTTODO/iOS-NOTTODO.xcodeproj/project.pbxproj
  iOS-NOTTODO/iOS-NOTTODO/Application/SceneDelegate.swift
  iOS-NOTTODO/iOS-NOTTODO/Global/Extensions/UI/UIColor+.swift
  iOS-NOTTODO/iOS-NOTTODO/Global/Extensions/UIScreen+.swift
  iOS-NOTTODO/iOS-NOTTODO/Global/Extensions/UIViewController+.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Achievement/AchievementViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Auth/AuthViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/HomeViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/MyInfo/MyInfoViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/TabBar/TabBarController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/TabBar/TabBarItem.swift
  iOS-NOTTODO/iOS-NOTTODO/Resource/Colors/Colors.xcassets/White.colorset/Contents.json
Labels: Chore, 윤서

#6 [Chore] #5 - .swiftlint 추가
  iOS-NOTTODO/.swiftlint.yml
  iOS-NOTTODO/iOS-NOTTODO.xcodeproj/project.pbxproj
Labels: Chore, 윤서

#8 [Chore] #7 - Swift Lint Github Action 추가
  .github/workflows/swiftlint.yml
  iOS-NOTTODO/iOS-NOTTODO/Application/AppDelegate.swift
  iOS-NOTTODO/iOS-NOTTODO/Application/SceneDelegate.swift
Labels: Chore, 윤서

#13 [Add] #12 - 필요한 Extention 추가 및 폴더링 변경
  iOS-NOTTODO/iOS-NOTTODO.xcodeproj/project.pbxproj
  iOS-NOTTODO/iOS-NOTTODO/Global/Extensions/Design/UIColor+.swift
  iOS-NOTTODO/iOS-NOTTODO/Global/Extensions/Design/UIFont+.swift
  iOS-NOTTODO/iOS-NOTTODO/Global/Extensions/Design/UIImage+.swift
  iOS-NOTTODO/iOS-NOTTODO/Global/Extensions/UILabel+.swift
  iOS-NOTTODO/iOS-NOTTODO/Global/Extensions/UIStackView+.swift
  iOS-NOTTODO/iOS-NOTTODO/Global/Extensions/UITextField+.swift
  iOS-NOTTODO/iOS-NOTTODO/Global/Extensions/UITextView+.swift
  iOS-NOTTODO/iOS-NOTTODO/Global/Extensions/UIView+.swift
  iOS-NOTTODO/iOS-NOTTODO/Global/Extensions/UIViewController+.swift
Labels: Add, 윤서

#14 [Feat] 카카오/애플 로그인 연결
  iOS-NOTTODO/iOS-NOTTODO.xcodeproj/project.pbxproj
  iOS-NOTTODO/iOS-NOTTODO/Application/AppDelegate.swift
  iOS-NOTTODO/iOS-NOTTODO/Application/SceneDelegate.swift
  iOS-NOTTODO/iOS-NOTTODO/Global/Literals/Strings.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/Base/GeneralResponse.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/Base/NetworkBase.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/Base/NetworkConstant.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/Base/NetworkLoggerPlugin.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/Base/NetworkResult.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/Base/URLConstant.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Auth/AuthViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Auth/ViewControllers/AuthViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Resource/Info.plist
  iOS-NOTTODO/iOS-NOTTODO/iOS-NOTTODO.entitlements
Labels: Feat, 민서

#16 [Feat] 추천 뷰 UI 구현
  iOS-NOTTODO/iOS-NOTTODO.xcodeproj/project.pbxproj
  iOS-NOTTODO/iOS-NOTTODO/Global/Extensions/Design/UIImage+.swift
  iOS-NOTTODO/iOS-NOTTODO/Global/Literals/Strings.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Common/PaddingLabel/PaddingLabel.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Recommend/Cells/RecommendCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Recommend/Models/RecommendModel.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Recommend/ViewControllers/RecommendActionViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Recommend/ViewControllers/RecommendViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/recommend/ic_delete_recommend.imageset/Contents.json
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/recommend/ic_delete_recommend.imageset/Vector.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/recommend/ic_delete_recommend.imageset/Vector@2x.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/recommend/ic_delete_recommend.imageset/Vector@3x.png
Labels: Feat, 민서

#19 [Design] 추천 뷰 - 실천 행동 선택 뷰 UI 구현
  iOS-NOTTODO/iOS-NOTTODO.xcodeproj/project.pbxproj
  iOS-NOTTODO/iOS-NOTTODO/Global/Extensions/Design/UIImage+.swift
  iOS-NOTTODO/iOS-NOTTODO/Global/Extensions/UIButton+.swift
  iOS-NOTTODO/iOS-NOTTODO/Global/Literals/Strings.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Recommend/Cells/RecommendCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Recommend/ViewControllers/RecommendActionViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Recommend/ViewControllers/RecommendViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/RecommendAction/Cells/RecommendActionCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/RecommendAction/Cells/RecommendActionFooterView.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/RecommendAction/Cells/RecommendActionHeaderView.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/RecommendAction/Models/RecommendActionModel.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/RecommendAction/ViewControllers/RecommendActionViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/recommend/ic_back_recommend.imageset/Contents.json
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/recommend/ic_back_recommend.imageset/Vector 1126.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/recommend/ic_back_recommend.imageset/Vector 1126@2x.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/recommend/ic_back_recommend.imageset/Vector 1126@3x.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/recommendAction/Contents.json
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/recommendAction/ic_arrow.imageset/Contents.json
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/recommendAction/ic_arrow.imageset/Vector 1114.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/recommendAction/ic_arrow.imageset/Vector 1114@2x.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/recommendAction/ic_arrow.imageset/Vector 1114@3x.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/recommendAction/ic_info.imageset/Contents.json
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/recommendAction/ic_info.imageset/icon.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/recommendAction/ic_info.imageset/icon@2x.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/recommendAction/ic_info.imageset/icon@3x.png
Labels: Design, 민서
