Repository DO-NOTTO-DO/iOS-NOTTODO, pull requests merged in 2023-08, with the labels that each got.

#175 [Feat] #174 - 추천뷰 앰플리튜드 적용
  iOS-NOTTODO/iOS-NOTTODO/Global/Enum/AnalyticsEvent.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Recommend/ViewControllers/RecommendViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/RecommendAction/Cells/RecommendActionFooterView.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/RecommendAction/ViewControllers/RecommendActionViewController.swift
Labels: Feat, 민서

#176 [Feat] #169 - 생성/수정뷰 앰플리튜드 적용
  iOS-NOTTODO/iOS-NOTTODO.xcodeproj/project.pbxproj
  iOS-NOTTODO/iOS-NOTTODO/Global/Enum/AnalyticsEvent.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/NottodoCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/SituationCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/ViewControllers/AddMissionViewController.swift
Labels: Feat, 윤서

#178 [Chore] #177 - DisplayName 변경
  iOS-NOTTODO/iOS-NOTTODO.xcodeproj/project.pbxproj
Labels: Chore, 윤서

#180 [Fix] #179 - 추천 행동 상세 뷰 앰플리튜드 수정
  iOS-NOTTODO/iOS-NOTTODO/Presentation/RecommendAction/ViewControllers/RecommendActionViewController.swift
Labels: Fix, 민서

#182 [Feat] #181 - 앰플리튜드 userId 추가
  iOS-NOTTODO/iOS-NOTTODO/Network/DataModel/Auth/AuthResponseDTO.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Auth/AuthViewController.swift
Labels: Feat, 윤서
