Repository DO-NOTTO-DO/iOS-NOTTODO, pull requests merged in 2023-06, with the labels that each got.

#64 [Add] #63 - 온보딩 애니메이션 추가
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Common/Utils.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Onboarding/ViewControllers/FifthOnboardingViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Onboarding/ViewControllers/FourthOnboardingViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Onboarding/ViewControllers/SecondOnboardingViewController.swift
Labels: Add, 정은

#65 [Design] #60 - ModalView UI 구현
  iOS-NOTTODO/.swiftlint.yml
  iOS-NOTTODO/iOS-NOTTODO.xcodeproj/project.pbxproj
  iOS-NOTTODO/iOS-NOTTODO/Global/Enum/MyInfoURL.swift
  iOS-NOTTODO/iOS-NOTTODO/Global/Extensions/Design/UIFont+.swift
  iOS-NOTTODO/iOS-NOTTODO/Global/Extensions/Design/UIImage+.swift
  iOS-NOTTODO/iOS-NOTTODO/Global/Literals/Strings.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/ViewControllers/AddMissionViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Modal/NottodoModalViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Modal/Protocol/ModalProtocol.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Modal/QuitModalView.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Modal/WithdrawModalView.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/MyInfo/Viewcontrollers/MyInfoViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/MyInfoAccount/ViewControllers/MyInfoAccountViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/TabBar/TabBarController.swift
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/modal/Contents.json
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/modal/img_quit1.imageset/Contents.json
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/modal/img_quit1.imageset/img_quit1.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/modal/img_quit1.imageset/img_quit1@2x.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/modal/img_quit1.imageset/img_quit1@3x.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/modal/img_quit2.imageset/Contents.json
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/modal/img_quit2.imageset/img_quit2.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/modal/img_quit2.imageset/img_quit2@2x.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/modal/img_quit2.imageset/img_quit2@3x.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Fonts/Pretendard-Bold.otf
  iOS-NOTTODO/iOS-NOTTODO/Resource/Info.plist
Labels: Feat, Design, 윤서

#66 [Feat] 소셜 로그인 API 연결
  iOS-NOTTODO/iOS-NOTTODO.xcodeproj/project.pbxproj
  iOS-NOTTODO/iOS-NOTTODO/Application/AppDelegate.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/Base/AuthAPI.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/Base/AuthResponseDTO.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/Base/AuthService.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/Base/URLConstant.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Auth/AuthViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/MyInfoAccount/ViewControllers/MyInfoAccountViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Resource/Info.plist
Labels: Feat, 민서

#71 [Design] #70 - AppIcon 추가
  iOS-NOTTODO/iOS-NOTTODO.xcodeproj/project.pbxproj
  iOS-NOTTODO/iOS-NOTTODO/Application/SceneDelegate.swift
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/AppIcon.appiconset/100.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/AppIcon.appiconset/1024.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/AppIcon.appiconset/114.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/AppIcon.appiconset/120.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/AppIcon.appiconset/128.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/AppIcon.appiconset/144.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/AppIcon.appiconset/152.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/AppIcon.appiconset/16.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/AppIcon.appiconset/167.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/AppIcon.appiconset/180.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/AppIcon.appiconset/20.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/AppIcon.appiconset/256.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/AppIcon.appiconset/29.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/AppIcon.appiconset/32.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/AppIcon.appiconset/40.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/AppIcon.appiconset/50.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/AppIcon.appiconset/512.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/AppIcon.appiconset/57.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/AppIcon.appiconset/58.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/AppIcon.appiconset/60.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/AppIcon.appiconset/64.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/AppIcon.appiconset/72.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/AppIcon.appiconset/76.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/AppIcon.appiconset/80.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/AppIcon.appiconset/87.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS-NOTTODO/iOS-NOTTODO/Resource/Info.plist
Labels: Design, 윤서

#72 [FEAT] #69 - 추천 뷰 -> 생성 뷰 화면전환
  iOS-NOTTODO/iOS-NOTTODO/Global/Extensions/UIViewController+.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/ViewControllers/HomeViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Recommend/ViewControllers/RecommendViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/RecommendAction/Cells/RecommendActionFooterView.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/RecommendAction/ViewControllers/RecommendActionViewController.swift
Labels: Feat, 윤서

#75 [Feat] #73 - 추천 상황 키워드 조회 API 연결
  iOS-NOTTODO/iOS-NOTTODO.xcodeproj/project.pbxproj
  iOS-NOTTODO/iOS-NOTTODO/Network/API/AchieveAPI.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/API/AddMission/AddMissionAPI.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/API/Auth/AuthAPI.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/API/HomeAPI.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/API/Recommend/RecommendAPI.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/API/Recommend/RecommendActionAPI.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/Base/URLConstant.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/DataModel/AchieveCalendarResponseDTO.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/DataModel/AddAnotherDayResponseDTO.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/DataModel/AddMission/RecommendSituationResponseDTO.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/DataModel/Auth/AuthResponseDTO.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/DataModel/DailyMissionResponseDTO.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/DataModel/MissionDetailResponseDTO.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/DataModel/Recommend/RecommendActionResponseDTO.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/DataModel/Recommend/RecommendResponseDTO.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/DataModel/WeekMissionResponseDTO.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/Service/AchieveService.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/Service/AddMission/AddMissionService.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/Service/Auth/AuthService.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/Service/HomeSevice.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/Service/Recommend/RecommendActionService.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/Service/Recommend/RecommendService.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/RecommendKeywordCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/SituationCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Models/RecommendKewordModels.swift
Labels: Feat, 윤서

#76 [Fix] #74 - 탈퇴 모달 flow 변경
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Modal/NottodoModalViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Recommend/ViewControllers/RecommendViewController.swift
Labels: Fix, 윤서

#78 [Feat] 자동 로그인 구현
  iOS-NOTTODO/iOS-NOTTODO.xcodeproj/xcshareddata/xcschemes/iOS-NOTTODO.xcscheme
  iOS-NOTTODO/iOS-NOTTODO/Application/AppDelegate.swift
  iOS-NOTTODO/iOS-NOTTODO/Application/SceneDelegate.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Auth/AuthViewController.swift
Labels: Feat, 민서

#79 [Fix] #62 - 홈 주간 캘린더 뷰 전환 및 성취뷰 수정
  iOS-NOTTODO/iOS-NOTTODO.xcodeproj/project.pbxproj
  iOS-NOTTODO/iOS-NOTTODO/Application/AppDelegate.swift
  iOS-NOTTODO/iOS-NOTTODO/Application/SceneDelegate.swift
  iOS-NOTTODO/iOS-NOTTODO/Global/Enum/DefaultKeys.swift
  iOS-NOTTODO/iOS-NOTTODO/Global/Enum/KeychainUtil.swift
  iOS-NOTTODO/iOS-NOTTODO/Global/Enum/MyInfoURL.swift
  iOS-NOTTODO/iOS-NOTTODO/Global/Extensions/String+.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/Base/NetworkConstant.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/Service/Auth/AuthService.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Achievement/ViewControllers/AchievementViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Achievement/ViewControllers/DetailAchievementViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Auth/AuthViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Common/Calendar/CalendarView.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Common/Calendar/WeekMonthFSCalendar.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/Model/MissionListModel.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/ViewControllers/DetailCalendarViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/ViewControllers/HomeViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/ViewControllers/MissionDetailViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Modal/NottodoModalViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/MyInfo/Model/MyInfoModel.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/MyInfo/Viewcontrollers/MyInfoViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/MyInfoAccount/ViewControllers/MyInfoAccountViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Onboarding/ViewControllers/FifthOnboardingViewController.swift
Labels: Fix, Add, 정은

#83 [Fix] #82 - 내 정보 뷰 코드 수정
  iOS-NOTTODO/iOS-NOTTODO/Application/AppDelegate.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/MyInfoAccount/ViewControllers/MyInfoAccountStackView.swift
Labels: Fix, 민서

#86 [Fix] #84 - 홈뷰 디자인요소 수정
  iOS-NOTTODO/iOS-NOTTODO.xcodeproj/project.pbxproj
  iOS-NOTTODO/iOS-NOTTODO/Global/Extensions/Design/UIImage+.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/Cells/HomeEmptyCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/Cells/MissionDetailCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/ViewControllers/MissionDetailViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/MyInfo/Model/MyInfoModel.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Onboarding/ViewControllers/FifthOnboardingViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Onboarding/ViewControllers/FourthOnboardingViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Onboarding/ViewControllers/ThirdOnboardingViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/IC/ic_question1.imageset/Contents.json
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/IC/ic_question1.imageset/icon.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/IC/ic_question1.imageset/icon@2x.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/IC/ic_question1.imageset/icon@3x.png
Labels: Fix, 정은

#85 [Fix] #80 - 소셜 로그인 코드 수정
  iOS-NOTTODO/iOS-NOTTODO/Application/AppDelegate.swift
  iOS-NOTTODO/iOS-NOTTODO/Global/Literals/Strings.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Auth/AuthViewController.swift
Labels: Fix, 민서

#92 [Design] #91 - 낫투두 생성 뷰 토글 닫혔을 때 UI 구현
  iOS-NOTTODO/iOS-NOTTODO/Global/Literals/Strings.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/ActionCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/DateCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/GoalCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/NottodoCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/SituationCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Components/AddMissionLabel/AddMissionLabel.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/ViewControllers/AddMissionViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/RecommendAction/Cells/RecommendActionCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/RecommendAction/Cells/RecommendActionHeaderView.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/RecommendAction/ViewControllers/RecommendActionViewController.swift
Labels: Design, 윤서

#94 [Design] #93 - 생성뷰 셀 상태에 따른 세 가지 UI 상태 구현
  iOS-NOTTODO/iOS-NOTTODO.xcodeproj/project.pbxproj
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/ActionCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/DateCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/GoalCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/NottodoCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/SituationCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Components/AddMissionTextFieldView/AddMissionTextFieldView.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Protocol/AddMissionProtocol.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/ViewControllers/AddMissionViewController.swift
Labels: Feat, Design, 윤서

#97 [Fix] #96 - 성취뷰 뷰전환 시 데이터 로드 수정
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Achievement/ViewControllers/AchievementViewController.swift
Labels: Fix, 정은

#99 [Feat] #95 - 낫투두 날짜 데이터 전달 및 UI 구현
  iOS-NOTTODO/iOS-NOTTODO.xcodeproj/project.pbxproj
  iOS-NOTTODO/iOS-NOTTODO/Global/Literals/Strings.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/ActionCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/DateCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/GoalCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/NottodoCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/SituationCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Protocol/AddMissionProtocol.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/ViewControllers/AddMissionViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/ViewControllers/HomeViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Recommend/ViewControllers/RecommendViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/RecommendAction/ViewControllers/RecommendActionViewController.swift
Labels: Feat, Design, 윤서

#101 [Feat] #100 - 낫투두 생성 API 연결
  iOS-NOTTODO/iOS-NOTTODO.xcodeproj/project.pbxproj
  iOS-NOTTODO/iOS-NOTTODO/Network/API/AddMission/AddMissionAPI.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/Base/URLConstant.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/DataModel/AddMission/AddMissionResponseDTO.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/Service/AddMission/AddMissionService.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/ViewControllers/AddMissionViewController.swift
Labels: Feat, 윤서

#106 [Feat] #102 - 낫투두 수정 API 연결
  iOS-NOTTODO/iOS-NOTTODO.xcodeproj/project.pbxproj
  iOS-NOTTODO/iOS-NOTTODO/Global/Literals/Strings.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/API/AddMission/AddMissionAPI.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/Base/URLConstant.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/DataModel/AddMission/UpdateMissionResponseDTO.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/Service/AddMission/AddMissionService.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/ViewControllers/AddMissionViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/ViewControllers/HomeViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/ViewControllers/MissionDetailViewController.swift
Labels: Feat, Design, 윤서

#110 [Feat] #107 - 낫투두 최근 기록 조회 API 연결
  iOS-NOTTODO/iOS-NOTTODO.xcodeproj/project.pbxproj
  iOS-NOTTODO/iOS-NOTTODO/Network/API/AddMission/AddMissionAPI.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/Base/URLConstant.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/DataModel/AddMission/RecentMissionResponseDTO.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/Service/AddMission/AddMissionService.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/MissionHistoryCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/NottodoCollectionViewCell.swift
Labels: Feat, 윤서

#108 [Fix] #105 - 캘린더 이미지뷰 사이즈 수정
  iOS-NOTTODO/iOS-NOTTODO.xcodeproj/project.pbxproj
  iOS-NOTTODO/iOS-NOTTODO/Network/API/Achieve/AchieveAPI.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/API/Auth/AuthAPI.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/API/Home/HomeAPI.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/Base/URLConstant.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/DataModel/Achieve/AchieveCalendarResponseDTO.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/DataModel/Home/AddAnotherDayResponseDTO.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/DataModel/Home/DailyMissionResponseDTO.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/DataModel/Home/MissionDetailResponseDTO.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/DataModel/Home/WeekMissionResponseDTO.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/Service/Achieve/AchieveService.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/Service/Auth/AuthService.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/Service/Home/HomeSevice.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Common/MissionCalendarCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Modal/NottodoModalViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/MyInfoAccount/ViewControllers/MyInfoAccountViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/IC/ic_date100.imageset/ic_date100.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/IC/ic_date100.imageset/ic_date100@2x.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/IC/ic_date100.imageset/ic_date100@3x.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/IC/ic_date50.imageset/ic_date50.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/IC/ic_date50.imageset/ic_date50@2x.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/IC/ic_date50.imageset/ic_date50@3x.png
Labels: Fix, 정은

#119 [Fix] #118 - 온보딩 애니메이션 뷰 수정
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Onboarding/Cell/OnboardingCollectionViewCell.swift
Labels: Fix, 정은

#121 [Design] #120 - 로그아웃 alert뷰 구현
  iOS-NOTTODO/iOS-NOTTODO/Global/Literals/Strings.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/MyInfoAccount/ViewControllers/MyInfoAccountViewController.swift
Labels: Design, 정은

#122 [Fix] #116 - 로그인 로직 수정
  iOS-NOTTODO/iOS-NOTTODO/Application/AppDelegate.swift
  iOS-NOTTODO/iOS-NOTTODO/Global/Enum/DefaultKeys.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/API/Auth/AuthAPI.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/Service/Auth/AuthService.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Auth/AuthViewController.swift
Labels: Fix, 민서

#125 [Fix] 로그인 로직 수정
  iOS-NOTTODO/iOS-NOTTODO/Global/Enum/DefaultKeys.swift
  iOS-NOTTODO/iOS-NOTTODO/Global/Enum/KeychainUtil.swift
  iOS-NOTTODO/iOS-NOTTODO/Global/Literals/Strings.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Auth/AuthViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/MyInfo/Viewcontrollers/MyInfoViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/MyInfoAccount/ViewControllers/MyInfoAccountViewController.swift
Labels: Fix, 민서

#128 [Fix] #117 - 온보딩 mp4 파일 수정
  iOS-NOTTODO/iOS-NOTTODO.xcodeproj/project.pbxproj
  iOS-NOTTODO/iOS-NOTTODO/Application/AppDelegate.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Onboarding/Lottie/logo.mp4
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Onboarding/Lottie/아요_로고.mp4
Labels: Fix, 민서

#127 [Design] #123 - 삭제하기 뷰 구현
  iOS-NOTTODO/iOS-NOTTODO.xcodeproj/project.pbxproj
  iOS-NOTTODO/iOS-NOTTODO/Global/Extensions/Design/UIImage+.swift
  iOS-NOTTODO/iOS-NOTTODO/Global/Literals/Strings.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/ViewControllers/HomeDeleteViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/ViewControllers/HomeViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Modal/DeleteModalView.swift
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/IC/ic_trashbin.imageset/Contents.json
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/IC/ic_trashbin.imageset/ic_trashbin.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/IC/ic_trashbin.imageset/ic_trashbin@2x.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/IC/ic_trashbin.imageset/ic_trashbin@3x.png
Labels: Design, 정은

#129 [Feat] #109 - 로그아웃 및 탈퇴 API 연결
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/ViewControllers/MissionDetailViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/MyInfo/Viewcontrollers/MyInfoViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/MyInfoAccount/ViewControllers/MyInfoAccountViewController.swift
Labels: Feat, 정은

#130 [Fix] #111 - 회원탈퇴 플로우 변경
  iOS-NOTTODO/iOS-NOTTODO.xcodeproj/project.pbxproj
  iOS-NOTTODO/iOS-NOTTODO/Global/Extensions/UIViewController+.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Modal/NottodoModalViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/MyInfoAccount/ViewControllers/MyInfoAccountViewController.swift
Labels: Fix, 윤서

#135 [Feat] #131 - 낫투두 생성/수정 시 예외처리 토스트 메세지 구현
  iOS-NOTTODO/iOS-NOTTODO.xcodeproj/project.pbxproj
  iOS-NOTTODO/iOS-NOTTODO/Global/Extensions/CALayer+.swift
  iOS-NOTTODO/iOS-NOTTODO/Global/Extensions/Design/UIImage+.swift
  iOS-NOTTODO/iOS-NOTTODO/Global/Extensions/UIViewController+.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/ViewControllers/AddMissionViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Common/Modal/DeleteModalView.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Common/Modal/NottodoModalViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Common/Modal/Protocol/ModalProtocol.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Common/Modal/QuitModalView.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Common/Modal/WithdrawModalView.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Common/Toast/NottodoToastView.swift
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/IC/ic_toast_error.imageset/Contents.json
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/IC/ic_toast_error.imageset/Group 35770.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/IC/ic_toast_error.imageset/Group 35770@2x.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/IC/ic_toast_error.imageset/Group 35770@3x.png
Labels: Feat, Design, 윤서

#137 [Feat] #134 - 홈뷰에서 수정뷰 전환
  iOS-NOTTODO/.swiftlint.yml
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/ViewControllers/AddMissionViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/Cells/DetailFooterReusableView.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/Cells/DetailHeaderReusableView.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/Cells/HomeEmptyCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/Cells/MissionDetailCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/Cells/MissionListCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/ViewControllers/DetailCalendarViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/ViewControllers/HomeViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/ViewControllers/MissionDetailViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Onboarding/ViewControllers/FifthOnboardingViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Onboarding/ViewControllers/FourthOnboardingViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Onboarding/ViewControllers/GradientView.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Onboarding/ViewControllers/OnboardingFooterView.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Onboarding/ViewControllers/OnboardingHeaderView.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Onboarding/ViewControllers/SecondOnboardingViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Onboarding/ViewControllers/ThirdOnboardingViewController.swift
Labels: Fix, Feat, 정은

#140 [Fix] #139 - 홈 상세보기뷰 데이터에 따른 UI 수정
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/Cells/MissionDetailCollectionViewCell.swift
Labels: Fix, 정은

#142 [Fix] #141 - 홈 상세보기, 다른 날짜 추가 UI 수정
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/Cells/MissionDetailCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/ViewControllers/DetailCalendarViewController.swift
Labels: Fix, Add, 정은
