Repository DO-NOTTO-DO/iOS-NOTTODO, pull requests merged in 2023-11, with the labels that each got.

#188 [Fix] #187 - 앰플리튜드 complete_create_mission 누락 추가
  iOS-NOTTODO/iOS-NOTTODO/Global/Enum/AnalyticsEvent.swift
  iOS-NOTTODO/iOS-NOTTODO/Global/Extensions/UIImageView+.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/ViewControllers/AddMissionViewController.swift
Labels: Fix, 혜수

#189 [Fix] #186 - 앰플리튜드 close_detail_mission 수정
  iOS-NOTTODO/iOS-NOTTODO.xcodeproj/project.pbxproj
  iOS-NOTTODO/iOS-NOTTODO/Global/Protocol/AmplitudeAnalyticsService.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Auth/AuthViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/ViewControllers/MissionDetailViewController.swift
Labels: Fix, 정은

#191 [Fix] #190 - 앱 버전 정보 수정
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Common/Utils.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/MyInfo/Model/MyInfoModel.swift
  iOS-NOTTODO/iOS-NOTTODO/Resource/Info.plist
Labels: Fix, 정은

#192 [Feat] #185 - 푸시 알림 구현
  iOS-NOTTODO/iOS-NOTTODO.xcodeproj/project.pbxproj
  iOS-NOTTODO/iOS-NOTTODO/Application/AppDelegate.swift
  iOS-NOTTODO/iOS-NOTTODO/Global/Enum/DefaultKeys.swift
  iOS-NOTTODO/iOS-NOTTODO/Global/Enum/KeychainUtil.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Auth/AuthViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Common/Modal/NottodoModalViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Resource/GoogleService-Info.plist
  iOS-NOTTODO/iOS-NOTTODO/Resource/Info.plist
  iOS-NOTTODO/iOS-NOTTODO/iOS-NOTTODO.entitlements
Labels: Feat, 윤서
