Repository DO-NOTTO-DO/iOS-NOTTODO, pull requests merged in 2023-03, with the labels that each got.

#21 [Design] 홈뷰 - 낫투두 리스트 UI 구현
  iOS-NOTTODO/iOS-NOTTODO.xcodeproj/project.pbxproj
  iOS-NOTTODO/iOS-NOTTODO/Global/Extensions/UITabBar+.swift
  iOS-NOTTODO/iOS-NOTTODO/Global/Literals/Strings.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Common/CompositionalLayout.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/Cells/HomeEmptyCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/Cells/MissionListCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/HomeViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/MissionListModel.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/ViewControllers/HomeViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/TabBar/TabBarController.swift
Labels: Chore, Feat, Design, 정은

#24 [Design] 홈뷰 - 캘린더 UI 구현
  iOS-NOTTODO/iOS-NOTTODO.xcodeproj/project.pbxproj
  iOS-NOTTODO/iOS-NOTTODO/Global/Literals/Strings.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Common/CalendarView.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Common/Utils.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Common/WeekMonthFSCalendar.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/Cells/HomeEmptyCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/Cells/MissionListCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/MissionListModel.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/ViewControllers/HomeViewController.swift
Labels: Design, 정은

#25 [Design] 성취뷰 UI 구현
  iOS-NOTTODO/iOS-NOTTODO.xcodeproj/project.pbxproj
  iOS-NOTTODO/iOS-NOTTODO/Global/Literals/Strings.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Achievement/AchievementViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Achievement/StatisticsView.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Common/CalendarView.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Common/Utils.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Common/WeekMonthFSCalendar.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/ViewControllers/HomeViewController.swift
Labels: Design, 정은

#17 [Design] 로그인 뷰 UI 구현
  iOS-NOTTODO/iOS-NOTTODO.xcodeproj/project.pbxproj
  iOS-NOTTODO/iOS-NOTTODO/Global/Extensions/Design/UIColor+.swift
  iOS-NOTTODO/iOS-NOTTODO/Global/Extensions/Design/UIImage+.swift
  iOS-NOTTODO/iOS-NOTTODO/Global/Literals/Strings.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Auth/AuthButtonView.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Auth/AuthViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/Auth/ic_apple_logo.imageset/Contents.json
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/Auth/ic_apple_logo.imageset/ic_apple_logo.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/Auth/ic_apple_logo.imageset/ic_apple_logo@2x.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/Auth/ic_apple_logo.imageset/ic_apple_logo@3x.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/Auth/ic_kakao_logo.imageset/Contents.json
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/Auth/ic_kakao_logo.imageset/image 281.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/Auth/ic_kakao_logo.imageset/image 281@2x.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/Auth/ic_kakao_logo.imageset/image 281@3x.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Colors/Colors.xcassets/yellow.colorset/Contents.json
Labels: Design, 민서

#27 [Design] 내 정보뷰 UI 구현
  iOS-NOTTODO/iOS-NOTTODO.xcodeproj/project.pbxproj
  iOS-NOTTODO/iOS-NOTTODO/Global/Literals/Strings.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Common/CompositionalLayout.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/MyInfo/Cell/InfoCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/MyInfo/Cell/MyInfoHeaderCollectionReusableView.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/MyInfo/Cell/MyProfileCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/MyInfo/Model/MyInfoModel.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/MyInfo/MyInfoViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/MyInfo/Viewcontrollers/MyInfoViewController.swift
Labels: Design, 정은

#36 [Design] 내 정보 뷰 - 정보박스 터치시 뷰 UI 구현
  iOS-NOTTODO/iOS-NOTTODO.xcodeproj/project.pbxproj
  iOS-NOTTODO/iOS-NOTTODO/Global/Extensions/Design/UIImage+.swift
  iOS-NOTTODO/iOS-NOTTODO/Global/Literals/Strings.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Common/SwitchView.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/MyInfoAccount/Models/MyInfoAccountModel.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/MyInfoAccount/ViewControllers/MyInfoAccountStackView.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/MyInfoAccount/ViewControllers/MyInfoAccountViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/Auth/btn_login_forapple.imageset/Contents.json
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/Auth/btn_login_forapple.imageset/btn_login_forapple.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/Auth/btn_login_forapple.imageset/btn_login_forapple@2x.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/Auth/btn_login_forapple.imageset/btn_login_forapple@3x.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/Auth/btn_login_forkakao.imageset/Contents.json
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/Auth/btn_login_forkakao.imageset/btn_login_forkakao.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/Auth/btn_login_forkakao.imageset/btn_login_forkakao@2x.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/Auth/btn_login_forkakao.imageset/btn_login_forkakao@3x.png
Labels: Design, 민서

#29 [Design] 홈뷰 - 미션 상세뷰 UI 구현
  iOS-NOTTODO/iOS-NOTTODO.xcodeproj/project.pbxproj
  iOS-NOTTODO/iOS-NOTTODO/Global/Literals/Strings.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Achievement/AchievementViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Common/Calendar/CalendarView.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Common/Calendar/WeekMonthFSCalendar.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Common/Layout/CompositionalLayout.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Common/StackView/DetailStackView.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Common/Utils.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/Cells/DetailFooterReusableView.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/Cells/DetailHeaderReusableView.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/Cells/MissionDetailCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/Model/MissionListModel.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/ViewControllers/DetailCalendarViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/ViewControllers/HomeViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/ViewControllers/MissionDetailViewController.swift
Labels: Design, 정은

#37 [Design] 성취 뷰 - 캘린더 커스텀 셀 구현
  iOS-NOTTODO/iOS-NOTTODO.xcodeproj/project.pbxproj
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Achievement/AchievementViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Common/MissionCalendarCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/ViewControllers/HomeViewController.swift
Labels: Design, 정은

#39 [Design] #38 - 온보딩 뷰 구현
  iOS-NOTTODO/iOS-NOTTODO.xcodeproj/project.pbxproj
  iOS-NOTTODO/iOS-NOTTODO/Global/Extensions/Design/UIColor+.swift
  iOS-NOTTODO/iOS-NOTTODO/Global/Extensions/Design/UIImage+.swift
  iOS-NOTTODO/iOS-NOTTODO/Global/Literals/Strings.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Onboarding/Cell/OnboardingCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Onboarding/Cell/SubOnboardingCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Onboarding/Model/OnboardingModel.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Onboarding/ViewControllers/FifthOnboardingViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Onboarding/ViewControllers/FourthOnboardingViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Onboarding/ViewControllers/GradientView.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Onboarding/ViewControllers/OnboardingFooterView.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Onboarding/ViewControllers/OnboardingHeaderView.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Onboarding/ViewControllers/SecondOnboardingViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Onboarding/ViewControllers/ThirdOnboardingViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/splash/splash_arrow.imageset/Contents.json
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/splash/splash_arrow.imageset/Group 35698.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/splash/splash_arrow.imageset/Group 35698@2x.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/splash/splash_arrow.imageset/Group 35698@3x.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/splash/splash_create_back.imageset/Contents.json
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/splash/splash_create_back.imageset/ic_create_back.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/splash/splash_create_back.imageset/ic_create_back@2x.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/splash/splash_create_back.imageset/ic_create_back@3x.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Colors/Colors.xcassets/gray8.colorset/Contents.json
Labels: Design, 정은

#40 [Feat] #31 - 홈 뷰 - 상세뷰 화면 전환 구현
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/Cells/MissionListCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/Model/MissionListModel.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/ViewControllers/HomeViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/ViewControllers/MissionDetailViewController.swift
Labels: Feat

#41 [Design] #30 - 성취뷰 - 디테일 미션뷰 UI 구현
  iOS-NOTTODO/iOS-NOTTODO.xcodeproj/project.pbxproj
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Achievement/Cell/DetailAchievementCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Achievement/ViewControllers/AchievementViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Achievement/ViewControllers/DetailAchievementViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Achievement/ViewControllers/StatisticsView.swift
Labels: Design, 정은

#43 [Design] #9 - 낫투두 생성 뷰 UI 구현
  iOS-NOTTODO/iOS-NOTTODO.xcodeproj/project.pbxproj
  iOS-NOTTODO/iOS-NOTTODO/Application/SceneDelegate.swift
  iOS-NOTTODO/iOS-NOTTODO/Global/Extensions/UICollectionViewCell+.swift
  iOS-NOTTODO/iOS-NOTTODO/Global/Extensions/UIViewController+.swift
  iOS-NOTTODO/iOS-NOTTODO/Global/Literals/Strings.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/AddMissionViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/ActionCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/AddMissionFooterCollectionReusableView.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/DateCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/GoalCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/MissionHistoryCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/NottodoCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/RecommendKeywordCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/SituationCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Components/AddMissionLabel/AddMissionLabel.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Components/AddMissionTextFieldView/AddMissionTextFieldView.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Models/MissionHistoryModels.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Models/RecommendKewordModels.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Protocol/AddMissionProtocol.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/ViewControllers/AddMissionViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/image/img_create_tip.imageset/Contents.json
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/image/img_create_tip.imageset/Group 35624.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/image/img_create_tip.imageset/Group 35624@2x.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/image/img_create_tip.imageset/Group 35624@3x.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/image/img_create_tip.imageset/img_create_tip.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/image/img_create_tip.imageset/img_create_tip@2x.png
  iOS-NOTTODO/iOS-NOTTODO/Resource/Assets/Assets.xcassets/image/img_create_tip.imageset/img_create_tip@3x.png
Labels: Design, 윤서
