Repository DO-NOTTO-DO/iOS-NOTTODO, pull requests merged in 2023-07, with the labels that each got.

#147 [Fix] #145 - API KEY에 baseURL 추가 및 코드 수정
  iOS-NOTTODO/iOS-NOTTODO.xcodeproj/project.pbxproj
  iOS-NOTTODO/iOS-NOTTODO/Global/Extensions/Bundle+.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/Base/URLConstant.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/Service/Achieve/AchieveService.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/Service/AddMission/AddMissionService.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/Service/Auth/AuthService.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/Service/Home/HomeSevice.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/Service/Recommend/RecommendActionService.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/Service/Recommend/RecommendService.swift
Labels: Fix, 정은

#148 [Feat] #136 - 생성/수정 뷰 날짜 선택 UI 및 스와이프 화면전환 시 날짜 Text 수정
  iOS-NOTTODO/iOS-NOTTODO.xcodeproj/project.pbxproj
  iOS-NOTTODO/iOS-NOTTODO/Global/Literals/Strings.swift
  iOS-NOTTODO/iOS-NOTTODO/Network/API/AddMission/AddMissionAPI.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/DateCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/ViewControllers/AddMissionViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Common/Calendar/CalendarView.swift
Labels: Fix, Design, 윤서

#151 [Fix] #150 - 앰플리튜드 변경 사항 적용
  iOS-NOTTODO/iOS-NOTTODO/Global/Enum/AnalyticsEvent.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Achievement/ViewControllers/AchievementViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Achievement/ViewControllers/DetailAchievementViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/DateCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/ViewControllers/DetailCalendarViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/ViewControllers/HomeViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/ViewControllers/MissionDetailViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Onboarding/Model/OnboardingModel.swift
Labels: Fix, 정은

#146 [Fix] #126 - mp4 업데이트 및 QA 반영
  iOS-NOTTODO/iOS-NOTTODO.xcodeproj/project.pbxproj
  iOS-NOTTODO/iOS-NOTTODO/Application/AppDelegate.swift
  iOS-NOTTODO/iOS-NOTTODO/Global/Literals/Strings.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/MyInfo/Viewcontrollers/MyInfoViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Onboarding/Lottie/logo.mp4
Labels: Fix, 민서

#153 [Fix] #152 - 카카오톡 앱으로 로그인
  iOS-NOTTODO/iOS-NOTTODO.xcodeproj/project.pbxproj
  iOS-NOTTODO/iOS-NOTTODO/Application/SceneDelegate.swift
  iOS-NOTTODO/iOS-NOTTODO/Resource/API_KEY.plist
  iOS-NOTTODO/iOS-NOTTODO/Resource/Info.plist
Labels: Fix, 민서

#154 [Fix] #149 - 낫투두 생성 화면전환 플로우 수정 및 낫투두 수정 날짜 토글 수정
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/DateCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/ViewControllers/AddMissionViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Recommend/ViewControllers/RecommendViewController.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/RecommendAction/ViewControllers/RecommendActionViewController.swift
Labels: Fix, 윤서

#156 [Fix] #155 - 토글 입력값 수정
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/DateCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Components/AddMissionTextFieldView/AddMissionTextFieldView.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/ViewControllers/AddMissionViewController.swift
Labels: Fix, 윤서

#158 [Fix] #157 - 카카오 유저 닉네임 불러오기
  iOS-NOTTODO/iOS-NOTTODO.xcodeproj/project.pbxproj
  iOS-NOTTODO/iOS-NOTTODO/Global/Enum/DefaultKeys.swift
  iOS-NOTTODO/iOS-NOTTODO/Global/Enum/KeychainUtil.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/MyInfo/Viewcontrollers/MyInfoViewController.swift
Labels: Fix, 윤서

#160 [Fix] #159 - 생성/수정뷰 QA반영
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/ActionCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/DateCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/GoalCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/NottodoCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/SituationCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Components/AddMissionTextFieldView/AddMissionTextFieldView.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/ViewControllers/AddMissionViewController.swift
Labels: Fix, Design, 윤서

#162 [Fix] #161 - 날짜 토글 분기처리 수정
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/DateCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/ViewControllers/AddMissionViewController.swift
Labels: Fix, Design, 윤서

#166 [Fix] #165 - 생성/수정 뷰 UI QA 반영
  iOS-NOTTODO/iOS-NOTTODO.xcodeproj/project.pbxproj
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/DateCollectionViewCell.swift
Labels: Fix, 윤서

#168 [Feat] #167 - 1차 출시 최종 라이팅 워싱 반영
  iOS-NOTTODO/iOS-NOTTODO/Global/Literals/Strings.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/ActionCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/GoalCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/NottodoCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Components/AddMissionTextFieldView/AddMissionTextFieldView.swift
Labels: Feat, 윤서

#170 [Fix] #164 - 추천뷰 QA 반영
  iOS-NOTTODO/iOS-NOTTODO.xcodeproj/project.pbxproj
  iOS-NOTTODO/iOS-NOTTODO/Network/DataModel/Recommend/RecommendActionResponseDTO.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Recommend/Models/RecommendModel.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/RecommendAction/Cells/RecommendActionCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/RecommendAction/Cells/RecommendActionHeaderView.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/RecommendAction/Models/RecommendActionModel.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/RecommendAction/ViewControllers/RecommendActionViewController.swift
Labels: Fix, 민서

#172 [Chore] #171 - 오픈소스 라이선스 고지 추가
  iOS-NOTTODO/Settings.bundle/LicenseProject.latest_result.txt
  iOS-NOTTODO/Settings.bundle/LicenseProject.plist
  iOS-NOTTODO/Settings.bundle/LicenseProject/Alamofire.plist
  iOS-NOTTODO/Settings.bundle/LicenseProject/Amplitude-iOS.plist
  iOS-NOTTODO/Settings.bundle/LicenseProject/FSCalendar.plist
  iOS-NOTTODO/Settings.bundle/LicenseProject/Kingfisher.plist
  iOS-NOTTODO/Settings.bundle/LicenseProject/Moya.plist
  iOS-NOTTODO/Settings.bundle/LicenseProject/ReactiveSwift.plist
  iOS-NOTTODO/Settings.bundle/LicenseProject/RxSwift.plist
  iOS-NOTTODO/Settings.bundle/LicenseProject/SnapKit.plist
  iOS-NOTTODO/Settings.bundle/LicenseProject/Then.plist
  iOS-NOTTODO/Settings.bundle/LicenseProject/analytics-connector-ios.plist
  iOS-NOTTODO/Settings.bundle/LicenseProject/kakao-ios-sdk.plist
  iOS-NOTTODO/Settings.bundle/LicenseProject/lottie-ios.plist
  iOS-NOTTODO/Settings.bundle/Root.plist
  iOS-NOTTODO/Settings.bundle/en.lproj/Root.strings
  iOS-NOTTODO/iOS-NOTTODO.xcodeproj/project.pbxproj
  iOS-NOTTODO/iOS-NOTTODO/Presentation/MyInfo/Model/MyInfoModel.swift
Labels: Chore, 윤서

#173 [Fix] #163 - 홈 미션리스트 체크 버튼 터치 영역 수정
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/Cells/MissionListCollectionViewCell.swift
  iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/ViewControllers/HomeViewController.swift
Labels: Fix, 정은
